package com.example.myrestaurant_v2_kotlin.eventbus

import com.example.myrestaurant_v2_kotlin.model.PopularCategoryModel

data class PopularCategoryItemClick(var popularCategoryModel: PopularCategoryModel)